/var/log/nginx/*.log /var/log/nginx/**/*.log {
    su root root
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    sharedscripts
    postrotate
        # Envia senyal USR1 a nginx per reobrir els fitxers de log
        if [ -f /var/run/nginx.pid ]; then
            kill -USR1 $(cat /var/run/nginx.pid)
        fi
    endscript
}
